name: 'Java Deploy to Azure'

on:
  workflow_call:
    inputs:
      job_name:
        type: string
        required: true
      api_name:
        type: string
        required: true
      suffix:
        type: string
        required: true
    secrets:
      AZ_CREDENTIALS:
        required: true
      AZ_RESOURCE_NAME:
        required: true

jobs:
  build_test_analyse:
    name: ${{ inputs.job_name }}

    runs-on: ubuntu-latest

    steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "RESOURCE_GROUP_NAME=rg-${{ secrets.AZ_RESOURCE_NAME }}" >> $GITHUB_ENV
        echo "FUNCTION_APP_NAME=fncapp-${{ secrets.AZ_RESOURCE_NAME }}-${{ inputs.suffix }}" >> $GITHUB_ENV
        echo "API_APP_PATH=published/${{ inputs.api_name }}" >> $GITHUB_ENV

    # - name: Check environment variables
    #   shell: bash
    #   run: |
    #     echo $RESOURCE_GROUP_NAME
    #     echo $FUNCTION_APP_NAME
    #     echo $API_APP_PATH

    - name: Download FunctionApp artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.api_name }}_app
        path: ${{ env.API_APP_PATH }}

    - name: Login to Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZ_CREDENTIALS }}

    - name: Get FunctionApp publish profile
      id: publishprofile
      uses: aliencube/publish-profile-actions@v1
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZ_CREDENTIALS }}
      with:
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        appName: ${{ env.FUNCTION_APP_NAME }}

    - name: Deploy FunctionApp
      id: fncapp
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.FUNCTION_APP_NAME }}
        package: ${{ env.API_APP_PATH }}
        publish-profile: ${{ steps.publishprofile.outputs.profile }}

    - name: Reset FunctionApp publish profile
      uses: aliencube/publish-profile-actions@v1
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZ_CREDENTIALS }}
      with:
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        appName: ${{ env.FUNCTION_APP_NAME }}
        reset: true
